### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by timothy-ch-cheung** [timothy-ch-cheung/PositivityBot#1]
- [ ] Send different gifs rather than the same one
- [ ] Reply to username mentions if the body is not a username only
- [ ] add stats for rating of comment against previous ratings: e.g. "your comment was more positive than x% of comments"
